runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    SITE_NAME: "Promulgate"
    SITE_VERSION: "1.0.19"
    SITE_DEBUG: 1

    ASSETS_DIRECTORY=: "/assets/"
    CSS_PATH: "/assets/css"
    JS_PATH: "/assets/js"
    IMAGES_PATH: "/assets/images"

    API_USERNAME: "promulgate"
    API_PASSWORD: "promulgate"
    API_BASE_URL: "http://localhost:8080"
    API_BASE_URL_TEST: "http://ec2-65-0-9-53.ap-south-1.compute.amazonaws.com"

    SESSION_CUSTOM_NAME: "USER_TOKEN"
    SESSION_EXPIRY_SECONDS: "0"
    SESSION_EXPIRY_PATH: "/"
    SESSION_EXPIRY_DOMAIN: null
    SESSION_EXPIRY_SECURE: false
    SESSION_EXPIRY_HTTPONLY: false

    GOOGLE_OAUTH_CLIENT_ID: "679025676115-v51qtdr06e11guq87hovgp9srg07dblm.apps.googleusercontent.com"
    GOOGLE_YOUTUBE_API_KEY: "AIzaSyCmPX-4KQ-wjqFqJCYGGRtuYwqjY8s_jt4"
    GOOGLE_APP_ID: "679025676115"
    GOOGLE_DRIVE_API_KEY: "AIzaSyB7NL95dZWsll0ZbKU1pkMiMQ_Kt5ihfuk"

    FACEBOOK_APP_ID: "966574143999598"
    FACEBOOK_CLIENT_ID: "966574143999598"
    FACEBOOK_CLIENT_TOKEN: "c9829c0a9d7a3f1e18bb083737084278"
    FACEBOOK_CLIENT_SECRET: "90861765882861b31429528e43d1f288"
    FACEBOOK_GRAPH_API_VERSION: "v13.0"

    LINKEDIN_CLIENT_ID: "86qls8f8smvgeg"
    LINKEDIN_CLIENT_SECRET: "z8BZRyDCI3qlK6DB"
